# Generated by Django 4.2.4 on 2023-08-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MOBILE', 'Mobile'), ('SITES', 'Sites'), ('LANGIN_PAGES', 'Landing Pages')], default='', max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/d')),
                ('public_project', models.BooleanField(default=True)),
            ],
        ),
    ]
