# Generated by Django 4.2.4 on 2023-08-24 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_imagefieldsproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_publicated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
