# Generated by Django 4.2.4 on 2023-08-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_projects_date_publicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefieldsproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portifolio.projects'),
        ),
    ]
