# Generated by Django 4.2.4 on 2023-08-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_imagefieldsproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(related_name='projects', to='portifolio.imagefieldsproject'),
        ),
        migrations.AlterField(
            model_name='imagefieldsproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.projects'),
        ),
    ]
