# Generated by Django 4.2.4 on 2023-08-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_remove_projects_image_projects_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='images',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d/d'),
        ),
        migrations.AlterField(
            model_name='imagefieldsproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portifolio.projects'),
        ),
    ]
