# Generated by Django 4.2.4 on 2023-08-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_remove_projects_images_projects_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefieldsproject',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='project'),
        ),
    ]
