# Generated by Django 4.2.4 on 2023-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_alter_imagefieldsproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefieldsproject',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/d', verbose_name='project'),
        ),
    ]
